repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0 # Use the version of ruff you have installed
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: python
        types: [python]
        pass_filenames: false
        always_run: true
        additional_dependencies: [
            "pytest",
            "pytest-mock",
            "pytest-cov",
            "pytest-env",
            "pytest-anyio",
            "pytest-asyncio",
            "deepgram-sdk",
            "pychromecast",
            "zeroconf",
            "fastapi",
            "uvicorn",
            "pydantic",
            "pydantic-settings",
            "structlog",
            "python-dotenv",
            "slowapi",
            "httpx",
            "pytest-deadfixtures"
        ]